version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
      timezone: America/Chicago
    labels:
      - 🤖 dependabot
    groups:
      cargo:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      timezone: America/Chicago
    labels:
      - 🤖 dependabot
    groups:
      gha:
        patterns:
          - "*"
