[bumpver]
commit = true
commit_message = ":bookmark: bump version {old_version} -> {new_version}"
current_version = "0.1.0"
push = false
tag = false
version_pattern = "MAJOR.MINOR.PATCH[PYTAGNUM]"

[bumpver.file_patterns]
".bumpver.toml" = [
  '^current_version = "{version}"',
]
"Cargo.toml" = [
  '^version = "{version}"',
]
"extension.toml" = [
  '^version = "{version}"',
]
