id = "django"
name = "Django"
description = "Django support"
version = "0.2.0"
schema_version = 1
authors = ["Josh Thomas <josh@joshthomas.dev>"]
repository = "https://github.com/joshuadavidthomas/zed-django"

[language_servers.django-language-server]
name = "Django Language Server"
languages = ["Django"]

[language_servers.django-template-lsp]
name = "Django Template LSP"
languages = ["Django"]

[grammars.htmldjango]
repository = "https://github.com/joshuadavidthomas/tree-sitter-htmldjango"
commit = "60771d12aee60e4ccb220548d8a485c3aa4183cf"
