id = "django"
name = "Django"
description = "Django support"
version = "0.2.2"
schema_version = 1
authors = ["Josh Thomas <josh@joshthomas.dev>"]
repository = "https://github.com/joshuadavidthomas/zed-django"

[language_servers.django-language-server]
name = "Django Language Server"
languages = ["Django"]

[language_servers.django-template-lsp]
name = "Django Template LSP"
languages = ["Django"]

[grammars.htmldjango]
repository = "https://github.com/joshuadavidthomas/tree-sitter-htmldjango"
commit = "f2a095ecaa02817b709b398dcd96922624144723"
