name = "Django"
grammar = "htmldjango"

first_line_pattern = "^\\{%\\s*(extends|load)"
path_suffixes = ["dj.html", "dj.md", "dj.txt"]

block_comment = ["{% comment %}", " {% endcomment %}"]
line_comments = ["{# ", " #}"]

autoclose_before = "}])>"

brackets = [
    { start = "{{", end = "}}", close = true, newline = true },
    { start = "{%", end = "%}", close = true, newline = true },
    { start = "{#", end = "#}", close = true, newline = false },
]

word_characters = ["-"]

scope_opt_in_language_servers = ["tailwindcss-language-server"]
